DIR_CONF='/root'
DIR_LIBS='/DataVolume/dittodata/lib'
DIR_LOGS='/DataVolume/dittodata/logs'
DIR_MNTS='/DataVolume/dittodata/mnt'
DIR_TEMP='/DataVolume/dittodata/tmp'
LOG_ERRS="${RJN}.log"
LOG_FIFO="${RJN}.fifo"

ALERTS='all'
ALERT='https://dittodata.com/services/alert.php?sid=${SID}&type=${TYPE}&archive=${RJN}&size=${SIZE}&tag1=${TAG1}&tag2=${TAG2}&tag3=${TAG3}&tag4=${TAG4}'


TAG1='KLG'
TAG2=
TAG3=
TAG4=
