DIR_CONF='/root'
DIR_LOGS='/DataVolume/dittodata/logs'
DIR_MNTS='/DataVolume/dittodata/mnt'
DIR_TEMP='/DataVolume/dittodata/tmp'
LOG_ERRS="${RJN}.log"
LOG_FIFO="${RJN}.fifo"

ALERTS='all'
ALERT='http://ip.digital-pipe.com/code/backups.php?client=${TAG1}&type=${TYPE}&archive=${RJN}&size=${SIZE}'

TAG1='KLG'
TAG2=
TAG3=
TAG4=
