DIR_CONF='/root'
DIR_KEYS="/DataVolume/dittodata/keys"
DIR_LIBS='/DataVolume/dittodata/lib'
DIR_LOGS='/DataVolume/dittodata/logs'
DIR_MNTS='/DataVolume/dittodata/mnt'
DIR_TEMP='/DataVolume/dittodata/tmp'
LOG_ERRS="${RJN}.log"
LOG_FIFO="${RJN}.fifo"

ALERT_TYPE='post'
# If using your own alert service:
ALERT_CALL='https://www.dittodata.com/services/alert.php?status=${STATUS}&name=${NAME// /%20}&type=${TYPE}&archive=${RJN}&size=${SIZE}&tag1=${TAG1}&tag2=${TAG2}&tag3=${TAG3}&tag4=${TAG4}'
# If using the DittoData alert service:
#ALERT_CALL='https://www.dittodata.com/services/alert.php?account=${ACCOUNT}&sid=${SID}&status=${STATUS}&name=${NAME// /%20}&type=${TYPE}&archive=${RJN}&size=${SIZE}&tag1=${TAG1}&tag2=${TAG2}&tag3=${TAG3}&tag4=${TAG4}'


TAG1='KLG'
TAG2=
TAG3=
TAG4=
